user_families_paths = ["./config"]
mylang = "wikidata"
family = "wikidata"
usernames["my"]["my"] = "wikicom"
password_file = f"user-password.py"
minthrottle = 0
maxthrottle = 0
max_retries = 100
noisysleep = 30.0
# verbose_output = True
